./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/alley_1/frame_0005
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/alley_1/frame_0010
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/alley_1/frame_0015
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/alley_1/frame_0020
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/alley_1/frame_0025
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/alley_1/frame_0030
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/alley_1/frame_0035
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/alley_1/frame_0040
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/alley_1/frame_0045
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/alley_1/frame_0050
./labelFocalStack 13	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/alley_2/frame_0005
./labelFocalStack 13	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/alley_2/frame_0010
./labelFocalStack 13	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/alley_2/frame_0015
./labelFocalStack 12	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/alley_2/frame_0020
./labelFocalStack 12	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/alley_2/frame_0025
./labelFocalStack 13	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/alley_2/frame_0030
./labelFocalStack 13	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/alley_2/frame_0035
./labelFocalStack 13	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/alley_2/frame_0040
./labelFocalStack 13	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/alley_2/frame_0045
./labelFocalStack 13	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/alley_2/frame_0050
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/ambush_2/frame_0005
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/ambush_2/frame_0010
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/ambush_2/frame_0015
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/ambush_2/frame_0020
./labelFocalStack 12	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/ambush_4/frame_0005
./labelFocalStack 10	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/ambush_4/frame_0010
./labelFocalStack 9	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/ambush_4/frame_0015
./labelFocalStack 9	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/ambush_4/frame_0020
./labelFocalStack 7	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/ambush_4/frame_0025
./labelFocalStack 10	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/ambush_4/frame_0030
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/ambush_5/frame_0005
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/ambush_5/frame_0010
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/ambush_5/frame_0015
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/ambush_5/frame_0020
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/ambush_5/frame_0025
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/ambush_5/frame_0030
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/ambush_5/frame_0035
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/ambush_5/frame_0040
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/ambush_5/frame_0045
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/ambush_5/frame_0050
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/ambush_6/frame_0005
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/ambush_6/frame_0010
./labelFocalStack 10	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/ambush_6/frame_0015
./labelFocalStack 8	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/ambush_6/frame_0020
./labelFocalStack 2	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/ambush_7/frame_0005
./labelFocalStack 2	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/ambush_7/frame_0010
./labelFocalStack 2	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/ambush_7/frame_0015
./labelFocalStack 2	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/ambush_7/frame_0020
./labelFocalStack 2	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/ambush_7/frame_0025
./labelFocalStack 2	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/ambush_7/frame_0030
./labelFocalStack 2	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/ambush_7/frame_0035
./labelFocalStack 3	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/ambush_7/frame_0040
./labelFocalStack 3	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/ambush_7/frame_0045
./labelFocalStack 2	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/ambush_7/frame_0050
./labelFocalStack 9	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bamboo_1/frame_0005
./labelFocalStack 9	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bamboo_1/frame_0010
./labelFocalStack 9	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bamboo_1/frame_0015
./labelFocalStack 9	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bamboo_1/frame_0020
./labelFocalStack 9	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bamboo_1/frame_0025
./labelFocalStack 9	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bamboo_1/frame_0030
./labelFocalStack 8	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bamboo_1/frame_0035
./labelFocalStack 8	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bamboo_1/frame_0040
./labelFocalStack 8	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bamboo_1/frame_0045
./labelFocalStack 8	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bamboo_1/frame_0050
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bamboo_2/frame_0005
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bamboo_2/frame_0010
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bamboo_2/frame_0015
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bamboo_2/frame_0020
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bamboo_2/frame_0025
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bamboo_2/frame_0030
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bamboo_2/frame_0035
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bamboo_2/frame_0040
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bamboo_2/frame_0045
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bamboo_2/frame_0050
./labelFocalStack 5	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bandage_1/frame_0005
./labelFocalStack 5	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bandage_1/frame_0010
./labelFocalStack 5	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bandage_1/frame_0015
./labelFocalStack 5	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bandage_1/frame_0020
./labelFocalStack 5	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bandage_1/frame_0025
./labelFocalStack 5	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bandage_1/frame_0030
./labelFocalStack 5	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bandage_1/frame_0035
./labelFocalStack 5	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bandage_1/frame_0040
./labelFocalStack 5	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bandage_1/frame_0045
./labelFocalStack 6	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bandage_1/frame_0050
./labelFocalStack 8	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bandage_2/frame_0005
./labelFocalStack 8	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bandage_2/frame_0010
./labelFocalStack 8	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bandage_2/frame_0015
./labelFocalStack 8	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bandage_2/frame_0020
./labelFocalStack 8	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bandage_2/frame_0025
./labelFocalStack 8	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bandage_2/frame_0030
./labelFocalStack 8	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bandage_2/frame_0035
./labelFocalStack 8	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bandage_2/frame_0040
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bandage_2/frame_0045
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/bandage_2/frame_0050
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/cave_2/frame_0005
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/cave_2/frame_0010
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/cave_2/frame_0015
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/cave_2/frame_0020
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/cave_2/frame_0025
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/cave_2/frame_0030
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/cave_2/frame_0035
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/cave_2/frame_0040
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/cave_2/frame_0045
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/cave_2/frame_0050
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/cave_4/frame_0005
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/cave_4/frame_0010
./labelFocalStack 10	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/cave_4/frame_0015
./labelFocalStack 10	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/cave_4/frame_0020
./labelFocalStack 11	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/cave_4/frame_0025
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/cave_4/frame_0030
./labelFocalStack 11	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/cave_4/frame_0035
./labelFocalStack 12	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/cave_4/frame_0040
./labelFocalStack 12	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/cave_4/frame_0045
./labelFocalStack 13	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/cave_4/frame_0050
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/market_2/frame_0005
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/market_2/frame_0010
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/market_2/frame_0015
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/market_2/frame_0020
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/market_2/frame_0025
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/market_2/frame_0030
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/market_2/frame_0035
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/market_2/frame_0040
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/market_2/frame_0045
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/market_2/frame_0050
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/market_5/frame_0005
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/market_5/frame_0010
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/market_5/frame_0015
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/market_5/frame_0020
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/market_5/frame_0025
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/market_5/frame_0030
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/market_5/frame_0035
./labelFocalStack 8	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/market_5/frame_0040
./labelFocalStack 9	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/market_5/frame_0045
./labelFocalStack 11	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/market_5/frame_0050
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/market_6/frame_0005
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/market_6/frame_0010
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/market_6/frame_0015
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/market_6/frame_0020
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/market_6/frame_0025
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/market_6/frame_0030
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/market_6/frame_0035
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/market_6/frame_0040
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/mountain_1/frame_0005
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/mountain_1/frame_0010
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/mountain_1/frame_0015
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/mountain_1/frame_0020
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/mountain_1/frame_0025
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/mountain_1/frame_0030
./labelFocalStack 13	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/mountain_1/frame_0035
./labelFocalStack 12	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/mountain_1/frame_0040
./labelFocalStack 12	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/mountain_1/frame_0045
./labelFocalStack 12	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/mountain_1/frame_0050
./labelFocalStack 8	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/shaman_2/frame_0005
./labelFocalStack 8	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/shaman_2/frame_0010
./labelFocalStack 8	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/shaman_2/frame_0015
./labelFocalStack 8	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/shaman_2/frame_0020
./labelFocalStack 8	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/shaman_2/frame_0025
./labelFocalStack 8	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/shaman_2/frame_0030
./labelFocalStack 8	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/shaman_2/frame_0035
./labelFocalStack 8	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/shaman_2/frame_0040
./labelFocalStack 8	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/shaman_2/frame_0045
./labelFocalStack 8	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/shaman_2/frame_0050
./labelFocalStack 4	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/shaman_3/frame_0005
./labelFocalStack 4	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/shaman_3/frame_0010
./labelFocalStack 4	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/shaman_3/frame_0015
./labelFocalStack 4	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/shaman_3/frame_0020
./labelFocalStack 4	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/shaman_3/frame_0025
./labelFocalStack 4	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/shaman_3/frame_0030
./labelFocalStack 4	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/shaman_3/frame_0035
./labelFocalStack 4	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/shaman_3/frame_0040
./labelFocalStack 4	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/shaman_3/frame_0045
./labelFocalStack 4	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/shaman_3/frame_0050
./labelFocalStack 3	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/sleeping_1/frame_0005
./labelFocalStack 3	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/sleeping_1/frame_0010
./labelFocalStack 3	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/sleeping_1/frame_0015
./labelFocalStack 3	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/sleeping_1/frame_0020
./labelFocalStack 3	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/sleeping_1/frame_0025
./labelFocalStack 3	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/sleeping_1/frame_0030
./labelFocalStack 3	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/sleeping_1/frame_0035
./labelFocalStack 3	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/sleeping_1/frame_0040
./labelFocalStack 3	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/sleeping_1/frame_0045
./labelFocalStack 3	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/sleeping_1/frame_0050
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/sleeping_2/frame_0005
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/sleeping_2/frame_0010
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/sleeping_2/frame_0015
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/sleeping_2/frame_0020
./labelFocalStack 5	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/sleeping_2/frame_0025
./labelFocalStack 5	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/sleeping_2/frame_0030
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/sleeping_2/frame_0035
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/sleeping_2/frame_0040
./labelFocalStack 5	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/sleeping_2/frame_0045
./labelFocalStack 5	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/sleeping_2/frame_0050
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/temple_2/frame_0005
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/temple_2/frame_0010
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/temple_2/frame_0015
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/temple_2/frame_0020
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/temple_2/frame_0025
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/temple_2/frame_0030
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/temple_2/frame_0035
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/temple_2/frame_0040
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/temple_2/frame_0045
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/temple_2/frame_0050
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/temple_3/frame_0005
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/temple_3/frame_0010
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/temple_3/frame_0015
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/temple_3/frame_0020
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/temple_3/frame_0025
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/temple_3/frame_0030
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/temple_3/frame_0035
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/temple_3/frame_0040
./labelFocalStack 15	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/temple_3/frame_0045
./labelFocalStack 14	/media/saurabh/String/WORK/DATASETS/MPI-Sintel/fStack/temple_3/frame_0050
